import enum


class gamerule(enum.Enum):
	announceAdvancements = "announceAdvancements"
	commandBlockOutput = "commandBlockOutput"
	disableElytraMovementCheck = "disableElytraMovementCheck"
	disableRaids = "disableRaids"
	doDaylightCycle = "doDaylightCycle"
	doEntityDrops = "doEntityDrops"
	doFireTick = "doFireTick"
	doImmediateRespawn = "doImmediateRespawn"
	doInsomnia = "doInsomnia"
	doLimitedCrafting = "doLimitedCrafting"
	doMobLoot = "doMobLoot"
	doMobSpawning = "doMobSpawning"
	doPatrolSpawning = "doPatrolSpawning"
	doTileDrops = "doTileDrops"
	doTraderSpawning = "doTraderSpawning"
	doWeatherCycle = "doWeatherCycle"
	drowningDamage = "drowningDamage"
	fallDamage = "fallDamage"
	fireDamage = "fireDamage"
	forgiveDeadPlayers = "forgiveDeadPlayers"
	freezeDamage = "freezeDamage"
	keepInventory = "keepInventory"
	logAdminCommands = "logAdminCommands"
	maxCommandChainLength = "maxCommandChainLength"
	maxEntityCramming = "maxEntityCramming"
	mobGriefing = "mobGriefing"
	naturalRegeneration = "naturalRegeneration"
	playersSleepingPercentage = "playersSleepingPercentage"
	randomTickSpeed = "randomTickSpeed"
	reducedDebugInfo = "reducedDebugInfo"
	sendCommandFeedback = "sendCommandFeedback"
	showDeathMessages = "showDeathMessages"
	spawnRadius = "spawnRadius"
	spectatorsGenerateChunks = "spectatorsGenerateChunks"
	universalAnger = "universalAnger"
